//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetArmy.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Requests.
        /// </summary>
        public static string AccountRequests {
            get {
                return ResourceManager.GetString("AccountRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveCampKey {
            get {
                return ResourceManager.GetString("ActiveCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Campaing.
        /// </summary>
        public static string AddCampCastraKey {
            get {
                return ResourceManager.GetString("AddCampCastraKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new your service.
        /// </summary>
        public static string AddCCServiceKey {
            get {
                return ResourceManager.GetString("AddCCServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add foundling home service.
        /// </summary>
        public static string AddHomeKey {
            get {
                return ResourceManager.GetString("AddHomeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        public static string AddImageKey {
            get {
                return ResourceManager.GetString("AddImageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Pet.
        /// </summary>
        public static string AddMascotaKey {
            get {
                return ResourceManager.GetString("AddMascotaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddMascotaNameKey {
            get {
                return ResourceManager.GetString("AddMascotaNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal shelter service .
        /// </summary>
        public static string AddShelterKey {
            get {
                return ResourceManager.GetString("AddShelterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Account Requests.
        /// </summary>
        public static string AdminAccountRequests {
            get {
                return ResourceManager.GetString("AdminAccountRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopted.
        /// </summary>
        public static string Adopted {
            get {
                return ResourceManager.GetString("Adopted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Alergic.
        /// </summary>
        public static string AlergiesKey {
            get {
                return ResourceManager.GetString("AlergiesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fields Are Required.
        /// </summary>
        public static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveButton {
            get {
                return ResourceManager.GetString("ApproveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Formatted Email. Ej: user@email.com.
        /// </summary>
        public static string BadFormattedEmail {
            get {
                return ResourceManager.GetString("BadFormattedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed.
        /// </summary>
        public static string BreedKey {
            get {
                return ResourceManager.GetString("BreedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A good name is just the beginning..
        /// </summary>
        public static string CampaignHelper {
            get {
                return ResourceManager.GetString("CampaignHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaing&apos;s Description.
        /// </summary>
        public static string CampCastraDescriptionInputKey {
            get {
                return ResourceManager.GetString("CampCastraDescriptionInputKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaing&apos;s Direction.
        /// </summary>
        public static string CampCastraDirectionInputKey {
            get {
                return ResourceManager.GetString("CampCastraDirectionInputKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaing&apos;s Name.
        /// </summary>
        public static string CampCastraNameInputKey {
            get {
                return ResourceManager.GetString("CampCastraNameInputKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string CampCastraTelephone {
            get {
                return ResourceManager.GetString("CampCastraTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaing&apos;s Phone.
        /// </summary>
        public static string CampCastraTelephoneInputKey {
            get {
                return ResourceManager.GetString("CampCastraTelephoneInputKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only whole numbers.
        /// </summary>
        public static string cantKey {
            get {
                return ResourceManager.GetString("cantKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select current cantón.
        /// </summary>
        public static string cantonLbl {
            get {
                return ResourceManager.GetString("cantonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string CapKey {
            get {
                return ResourceManager.GetString("CapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castrated.
        /// </summary>
        public static string CastratedKey {
            get {
                return ResourceManager.GetString("CastratedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundling home&apos;s email.
        /// </summary>
        public static string CCEmailKey {
            get {
                return ResourceManager.GetString("CCEmailKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can be your personal number.
        /// </summary>
        public static string ccNumberHintKey {
            get {
                return ResourceManager.GetString("ccNumberHintKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundling home&apos;s number.
        /// </summary>
        public static string ccPhoneNumberKey {
            get {
                return ResourceManager.GetString("ccPhoneNumberKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Foundling Home.
        /// </summary>
        public static string ccServiceBtn {
            get {
                return ResourceManager.GetString("ccServiceBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image collection.
        /// </summary>
        public static string collectionlbl {
            get {
                return ResourceManager.GetString("collectionlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccountKey {
            get {
                return ResourceManager.GetString("CreateAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your New Account!.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your shelter.
        /// </summary>
        public static string CreateNewShelterH1Key {
            get {
                return ResourceManager.GetString("CreateNewShelterH1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shelter.
        /// </summary>
        public static string CreateShelterBtnKey {
            get {
                return ResourceManager.GetString("CreateShelterBtnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Campaing.
        /// </summary>
        public static string DeleteCampCastraKey {
            get {
                return ResourceManager.GetString("DeleteCampCastraKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteKey {
            get {
                return ResourceManager.GetString("DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete shelter.
        /// </summary>
        public static string DeleteShelterBtnkey {
            get {
                return ResourceManager.GetString("DeleteShelterBtnkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item?.
        /// </summary>
        public static string DeletionConfirm {
            get {
                return ResourceManager.GetString("DeletionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionCampKey {
            get {
                return ResourceManager.GetString("DescriptionCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionKey {
            get {
                return ResourceManager.GetString("DescriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string DirectionCampKey {
            get {
                return ResourceManager.GetString("DirectionCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability.
        /// </summary>
        public static string Disability {
            get {
                return ResourceManager.GetString("Disability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Account.
        /// </summary>
        public static string DisableAccount {
            get {
                return ResourceManager.GetString("DisableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Campaing.
        /// </summary>
        public static string EditCampCastraKey {
            get {
                return ResourceManager.GetString("EditCampCastraKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pet.
        /// </summary>
        public static string EditPetKey {
            get {
                return ResourceManager.GetString("EditPetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your Shelter.
        /// </summary>
        public static string EditShelterKey {
            get {
                return ResourceManager.GetString("EditShelterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your profile.
        /// </summary>
        public static string EditUserKey {
            get {
                return ResourceManager.GetString("EditUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email_Admin {
            get {
                return ResourceManager.GetString("Email_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered email: user@email.com.
        /// </summary>
        public static string EmailHintKey {
            get {
                return ResourceManager.GetString("EmailHintKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Empty.
        /// </summary>
        public static string EmailIsEmpty {
            get {
                return ResourceManager.GetString("EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EmailKey {
            get {
                return ResourceManager.GetString("EmailKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Account.
        /// </summary>
        public static string EnableAccount {
            get {
                return ResourceManager.GetString("EnableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDateCampKey {
            get {
                return ResourceManager.GetString("EndDateCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Is Empty.
        /// </summary>
        public static string FirstNameIsEmpty {
            get {
                return ResourceManager.GetString("FirstNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your full name.
        /// </summary>
        public static string fullNameKey {
            get {
                return ResourceManager.GetString("fullNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicaped.
        /// </summary>
        public static string HandicapedKey {
            get {
                return ResourceManager.GetString("HandicapedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpKey {
            get {
                return ResourceManager.GetString("HelpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illness.
        /// </summary>
        public static string Illness {
            get {
                return ResourceManager.GetString("Illness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Is Empty.
        /// </summary>
        public static string LastNameIsEmpty {
            get {
                return ResourceManager.GetString("LastNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make default image.
        /// </summary>
        public static string makeDefKey {
            get {
                return ResourceManager.GetString("makeDefKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More About Me.
        /// </summary>
        public static string MoreAboutMe {
            get {
                return ResourceManager.GetString("MoreAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Feed.
        /// </summary>
        public static string MyFeedKey {
            get {
                return ResourceManager.GetString("MyFeedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Services.
        /// </summary>
        public static string MyServicesKey {
            get {
                return ResourceManager.GetString("MyServicesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaing Name.
        /// </summary>
        public static string NameCampKey {
            get {
                return ResourceManager.GetString("NameCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameKey {
            get {
                return ResourceManager.GetString("NameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Pet Profile.
        /// </summary>
        public static string NextPetProfile {
            get {
                return ResourceManager.GetString("NextPetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string NombreUserKey {
            get {
                return ResourceManager.GetString("NombreUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        public static string NonValidPhoneNumber {
            get {
                return ResourceManager.GetString("NonValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string OrKey {
            get {
                return ResourceManager.GetString("OrKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password: *****.
        /// </summary>
        public static string PasswordHelperKey {
            get {
                return ResourceManager.GetString("PasswordHelperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Empty.
        /// </summary>
        public static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordKey {
            get {
                return ResourceManager.GetString("PasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords Do Not Match.
        /// </summary>
        public static string PasswordNoMatch {
            get {
                return ResourceManager.GetString("PasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Should Be at Least 6 Characters.
        /// </summary>
        public static string PasswordNonMinimumSize {
            get {
                return ResourceManager.GetString("PasswordNonMinimumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will permanently delete the next pet:.
        /// </summary>
        public static string PetDeletionBodyText {
            get {
                return ResourceManager.GetString("PetDeletionBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet.
        /// </summary>
        public static string PetKey {
            get {
                return ResourceManager.GetString("PetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        public static string PetsKey {
            get {
                return ResourceManager.GetString("PetsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets Management.
        /// </summary>
        public static string PetsManagement {
            get {
                return ResourceManager.GetString("PetsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typed Adress.
        /// </summary>
        public static string physicalKey {
            get {
                return ResourceManager.GetString("physicalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileKey {
            get {
                return ResourceManager.GetString("ProfileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add foundling home service.
        /// </summary>
        public static string registerAsCasaCunakey {
            get {
                return ResourceManager.GetString("registerAsCasaCunakey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Email.
        /// </summary>
        public static string RegisterEmailHelperKey {
            get {
                return ResourceManager.GetString("RegisterEmailHelperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least 7 characters.
        /// </summary>
        public static string RegisterPassHelperKey {
            get {
                return ResourceManager.GetString("RegisterPassHelperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectButton {
            get {
                return ResourceManager.GetString("RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Account.
        /// </summary>
        public static string RequestAccount {
            get {
                return ResourceManager.GetString("RequestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Administrator Account.
        /// </summary>
        public static string RequestAdmin {
            get {
                return ResourceManager.GetString("RequestAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Adoption.
        /// </summary>
        public static string RequestAdoption {
            get {
                return ResourceManager.GetString("RequestAdoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Adoption With Data Below?.
        /// </summary>
        public static string RequestAdoptionPopUpTitle {
            get {
                return ResourceManager.GetString("RequestAdoptionPopUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested:.
        /// </summary>
        public static string RequestedDate {
            get {
                return ResourceManager.GetString("RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SaveCampKey {
            get {
                return ResourceManager.GetString("SaveCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveKey {
            get {
                return ResourceManager.GetString("SaveKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name.
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your photo.
        /// </summary>
        public static string SearchImageKey {
            get {
                return ResourceManager.GetString("SearchImageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your default image.
        /// </summary>
        public static string SelectImagesKey {
            get {
                return ResourceManager.GetString("SelectImagesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string selectImgKey {
            get {
                return ResourceManager.GetString("selectImgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Services.
        /// </summary>
        public static string ServicesH1Key {
            get {
                return ResourceManager.GetString("ServicesH1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter&apos;s adress.
        /// </summary>
        public static string ShelterDirInputKey {
            get {
                return ResourceManager.GetString("ShelterDirInputKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter&apos;s email.
        /// </summary>
        public static string ShelterEmailKey {
            get {
                return ResourceManager.GetString("ShelterEmailKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter.
        /// </summary>
        public static string ShelterKey {
            get {
                return ResourceManager.GetString("ShelterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter&apos;s name.
        /// </summary>
        public static string ShelterNameInputKey {
            get {
                return ResourceManager.GetString("ShelterNameInputKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include regional code.
        /// </summary>
        public static string ShelterNumberHintKey {
            get {
                return ResourceManager.GetString("ShelterNumberHintKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact phone number .
        /// </summary>
        public static string ShelterNumberKey {
            get {
                return ResourceManager.GetString("ShelterNumberKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sickness.
        /// </summary>
        public static string SickKey {
            get {
                return ResourceManager.GetString("SickKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with mail.
        /// </summary>
        public static string SignUpKey {
            get {
                return ResourceManager.GetString("SignUpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong!!.
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string SpeciesKey {
            get {
                return ResourceManager.GetString("SpeciesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Date.
        /// </summary>
        public static string StarDateCampKey {
            get {
                return ResourceManager.GetString("StarDateCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusKey {
            get {
                return ResourceManager.GetString("StatusKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your surname.
        /// </summary>
        public static string SurnameUserKey {
            get {
                return ResourceManager.GetString("SurnameUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TelephoneCampKey {
            get {
                return ResourceManager.GetString("TelephoneCampKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treated.
        /// </summary>
        public static string Treated {
            get {
                return ResourceManager.GetString("Treated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string UbicacionKey {
            get {
                return ResourceManager.GetString("UbicacionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information.
        /// </summary>
        public static string UpdateCampCastraBtnKey {
            get {
                return ResourceManager.GetString("UpdateCampCastraBtnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Image.
        /// </summary>
        public static string UpdateImageKey {
            get {
                return ResourceManager.GetString("UpdateImageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string updateKey {
            get {
                return ResourceManager.GetString("updateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        public static string UpdateShelterBtnKey {
            get {
                return ResourceManager.GetString("UpdateShelterBtnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update info.
        /// </summary>
        public static string UpdateUserInfoKey {
            get {
                return ResourceManager.GetString("UpdateUserInfoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Age.
        /// </summary>
        public static string userAgeKey {
            get {
                return ResourceManager.GetString("userAgeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username.
        /// </summary>
        public static string UsernameKey {
            get {
                return ResourceManager.GetString("UsernameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number.
        /// </summary>
        public static string userPhoneKey {
            get {
                return ResourceManager.GetString("userPhoneKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaxinated.
        /// </summary>
        public static string VaxxedKey {
            get {
                return ResourceManager.GetString("VaxxedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WeightKey {
            get {
                return ResourceManager.GetString("WeightKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
